name: chukan-seiki
favicon: null
layout_spectrum: 0.87703
typography_spectrum: 0.61302
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000735'
    - '#2223b1'
    - '#4f50cf'
    - '#bca0ea'
    - '#f9eef2'
  brandStrength: 0.5
  lightness: 0.3088949383236468
  saturation: 0.3834334861021489
  rhythmicContrast: 0.5
purpose: []
